### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by iphydf** [cleverca22/toxvpn#11]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7437980 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7437980 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff746937d in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff744b63c in std::locale::_Impl::_M_install_facet(std::locale::id const*, std::locale::facet const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                                  #3  0x000000000040ba84 in nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator>::dump(int) const ()
#4  0x0000000000408cda in saveConfig(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator>) ()
#5  0x000000000040b0c4 in main ()
```

**Comment by iphydf** [comment]
My bad, compiler flag -fno-rtti breaks it.
